/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AvnOption {
    'label': string;
    'selected': boolean;
    'value': string;
  }
  interface AvnSelect {
    'disabled': boolean;
    'options': any;
    'placeholder': string;
    'selectedValue': string;
    'value': any;
  }
}

declare global {


  interface HTMLAvnOptionElement extends Components.AvnOption, HTMLStencilElement {}
  var HTMLAvnOptionElement: {
    prototype: HTMLAvnOptionElement;
    new (): HTMLAvnOptionElement;
  };

  interface HTMLAvnSelectElement extends Components.AvnSelect, HTMLStencilElement {}
  var HTMLAvnSelectElement: {
    prototype: HTMLAvnSelectElement;
    new (): HTMLAvnSelectElement;
  };
  interface HTMLElementTagNameMap {
    'avn-option': HTMLAvnOptionElement;
    'avn-select': HTMLAvnSelectElement;
  }
}

declare namespace LocalJSX {
  interface AvnOption extends JSXBase.HTMLAttributes<HTMLAvnOptionElement> {
    'label'?: string;
    'selected'?: boolean;
    'value'?: string;
  }
  interface AvnSelect extends JSXBase.HTMLAttributes<HTMLAvnSelectElement> {
    'disabled'?: boolean;
    'onChange'?: (event: CustomEvent<any>) => void;
    'options'?: any;
    'placeholder'?: string;
    'selectedValue'?: string;
    'value'?: any;
  }

  interface IntrinsicElements {
    'avn-option': AvnOption;
    'avn-select': AvnSelect;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


